name: jest-snapshot-test-actions
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: snapshot-test:latest
      -
        name: run snapshot -test
        run: docker run -v `pwd`/:/usr/src/app/ snapshot-test:latest
