name: jest-snapshot-test-actions
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Build
        run: docker build -t snapshot-test:latest .
      -
        name: run snapshot -test
        run: docker run -v `pwd`/:/usr/src/app/ snapshot-test:latest
